//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("ModeloDominio", "EmpresaCliente", "Empresa", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Facturacion.CapaDatos.Empresa), "Cliente", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Facturacion.CapaDatos.Cliente))]

#endregion

namespace Facturacion.CapaDatos
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class ModeloDominioContainer : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto ModeloDominioContainer usando la cadena de conexión encontrada en la sección 'ModeloDominioContainer' del archivo de configuración de la aplicación.
        /// </summary>
        public ModeloDominioContainer() : base("name=ModeloDominioContainer", "ModeloDominioContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto ModeloDominioContainer.
        /// </summary>
        public ModeloDominioContainer(string connectionString) : base(connectionString, "ModeloDominioContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto ModeloDominioContainer.
        /// </summary>
        public ModeloDominioContainer(EntityConnection connection) : base(connection, "ModeloDominioContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Empresa> Empresas
        {
            get
            {
                if ((_Empresas == null))
                {
                    _Empresas = base.CreateObjectSet<Empresa>("Empresas");
                }
                return _Empresas;
            }
        }
        private ObjectSet<Empresa> _Empresas;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Persona> Personas
        {
            get
            {
                if ((_Personas == null))
                {
                    _Personas = base.CreateObjectSet<Persona>("Personas");
                }
                return _Personas;
            }
        }
        private ObjectSet<Persona> _Personas;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Empresas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToEmpresas(Empresa empresa)
        {
            base.AddObject("Empresas", empresa);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Personas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToPersonas(Persona persona)
        {
            base.AddObject("Personas", persona);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModeloDominio", Name="Cliente")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cliente : Persona
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Cliente.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        /// <param name="apellido">Valor inicial de la propiedad apellido.</param>
        /// <param name="email">Valor inicial de la propiedad email.</param>
        /// <param name="fechanacimiento">Valor inicial de la propiedad fechanacimiento.</param>
        /// <param name="sexo">Valor inicial de la propiedad sexo.</param>
        /// <param name="ciudad">Valor inicial de la propiedad ciudad.</param>
        public static Cliente CreateCliente(global::System.Int32 id, global::System.String nombre, global::System.String apellido, global::System.String email, global::System.DateTime fechanacimiento, global::System.Boolean sexo, global::System.String ciudad)
        {
            Cliente cliente = new Cliente();
            cliente.id = id;
            cliente.nombre = nombre;
            cliente.apellido = apellido;
            cliente.email = email;
            cliente.fechanacimiento = fechanacimiento;
            cliente.sexo = sexo;
            cliente.ciudad = ciudad;
            return cliente;
        }

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ModeloDominio", "EmpresaCliente", "Empresa")]
        public Empresa Empresa
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Empresa>("ModeloDominio.EmpresaCliente", "Empresa").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Empresa>("ModeloDominio.EmpresaCliente", "Empresa").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Empresa> EmpresaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Empresa>("ModeloDominio.EmpresaCliente", "Empresa");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Empresa>("ModeloDominio.EmpresaCliente", "Empresa", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModeloDominio", Name="Empresa")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(Sucursal))]
    [KnownTypeAttribute(typeof(Proveedor))]
    public partial class Empresa : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Empresa.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="ciudad">Valor inicial de la propiedad ciudad.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        public static Empresa CreateEmpresa(global::System.Int32 id, global::System.String ciudad, global::System.String nombre)
        {
            Empresa empresa = new Empresa();
            empresa.id = id;
            empresa.ciudad = ciudad;
            empresa.nombre = nombre;
            return empresa;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> celular
        {
            get
            {
                return _celular;
            }
            set
            {
                OncelularChanging(value);
                ReportPropertyChanging("celular");
                _celular = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("celular");
                OncelularChanged();
            }
        }
        private Nullable<global::System.Int32> _celular;
        partial void OncelularChanging(Nullable<global::System.Int32> value);
        partial void OncelularChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ciudad
        {
            get
            {
                return _ciudad;
            }
            set
            {
                OnciudadChanging(value);
                ReportPropertyChanging("ciudad");
                _ciudad = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ciudad");
                OnciudadChanged();
            }
        }
        private global::System.String _ciudad;
        partial void OnciudadChanging(global::System.String value);
        partial void OnciudadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String direccion
        {
            get
            {
                return _direccion;
            }
            set
            {
                OndireccionChanging(value);
                ReportPropertyChanging("direccion");
                _direccion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("direccion");
                OndireccionChanged();
            }
        }
        private global::System.String _direccion;
        partial void OndireccionChanging(global::System.String value);
        partial void OndireccionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> telefono
        {
            get
            {
                return _telefono;
            }
            set
            {
                OntelefonoChanging(value);
                ReportPropertyChanging("telefono");
                _telefono = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("telefono");
                OntelefonoChanged();
            }
        }
        private Nullable<global::System.Int32> _telefono;
        partial void OntelefonoChanging(Nullable<global::System.Int32> value);
        partial void OntelefonoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> rut
        {
            get
            {
                return _rut;
            }
            set
            {
                OnrutChanging(value);
                ReportPropertyChanging("rut");
                _rut = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rut");
                OnrutChanged();
            }
        }
        private Nullable<global::System.Int64> _rut;
        partial void OnrutChanging(Nullable<global::System.Int64> value);
        partial void OnrutChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String razonsocial
        {
            get
            {
                return _razonsocial;
            }
            set
            {
                OnrazonsocialChanging(value);
                ReportPropertyChanging("razonsocial");
                _razonsocial = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("razonsocial");
                OnrazonsocialChanged();
            }
        }
        private global::System.String _razonsocial;
        partial void OnrazonsocialChanging(global::System.String value);
        partial void OnrazonsocialChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String observacion
        {
            get
            {
                return _observacion;
            }
            set
            {
                OnobservacionChanging(value);
                ReportPropertyChanging("observacion");
                _observacion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("observacion");
                OnobservacionChanged();
            }
        }
        private global::System.String _observacion;
        partial void OnobservacionChanging(global::System.String value);
        partial void OnobservacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ModeloDominio", "EmpresaCliente", "Cliente")]
        public Cliente Cliente
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("ModeloDominio.EmpresaCliente", "Cliente").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("ModeloDominio.EmpresaCliente", "Cliente").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Cliente> ClienteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("ModeloDominio.EmpresaCliente", "Cliente");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Cliente>("ModeloDominio.EmpresaCliente", "Cliente", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModeloDominio", Name="Persona")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(Cliente))]
    public partial class Persona : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Persona.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        /// <param name="apellido">Valor inicial de la propiedad apellido.</param>
        /// <param name="email">Valor inicial de la propiedad email.</param>
        /// <param name="fechanacimiento">Valor inicial de la propiedad fechanacimiento.</param>
        /// <param name="sexo">Valor inicial de la propiedad sexo.</param>
        /// <param name="ciudad">Valor inicial de la propiedad ciudad.</param>
        public static Persona CreatePersona(global::System.Int32 id, global::System.String nombre, global::System.String apellido, global::System.String email, global::System.DateTime fechanacimiento, global::System.Boolean sexo, global::System.String ciudad)
        {
            Persona persona = new Persona();
            persona.id = id;
            persona.nombre = nombre;
            persona.apellido = apellido;
            persona.email = email;
            persona.fechanacimiento = fechanacimiento;
            persona.sexo = sexo;
            persona.ciudad = ciudad;
            return persona;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String apellido
        {
            get
            {
                return _apellido;
            }
            set
            {
                OnapellidoChanging(value);
                ReportPropertyChanging("apellido");
                _apellido = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("apellido");
                OnapellidoChanged();
            }
        }
        private global::System.String _apellido;
        partial void OnapellidoChanging(global::System.String value);
        partial void OnapellidoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fechanacimiento
        {
            get
            {
                return _fechanacimiento;
            }
            set
            {
                OnfechanacimientoChanging(value);
                ReportPropertyChanging("fechanacimiento");
                _fechanacimiento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fechanacimiento");
                OnfechanacimientoChanged();
            }
        }
        private global::System.DateTime _fechanacimiento;
        partial void OnfechanacimientoChanging(global::System.DateTime value);
        partial void OnfechanacimientoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean sexo
        {
            get
            {
                return _sexo;
            }
            set
            {
                OnsexoChanging(value);
                ReportPropertyChanging("sexo");
                _sexo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sexo");
                OnsexoChanged();
            }
        }
        private global::System.Boolean _sexo;
        partial void OnsexoChanging(global::System.Boolean value);
        partial void OnsexoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ciudad
        {
            get
            {
                return _ciudad;
            }
            set
            {
                OnciudadChanging(value);
                ReportPropertyChanging("ciudad");
                _ciudad = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ciudad");
                OnciudadChanged();
            }
        }
        private global::System.String _ciudad;
        partial void OnciudadChanging(global::System.String value);
        partial void OnciudadChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModeloDominio", Name="Proveedor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Proveedor : Empresa
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Proveedor.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="ciudad">Valor inicial de la propiedad ciudad.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        public static Proveedor CreateProveedor(global::System.Int32 id, global::System.String ciudad, global::System.String nombre)
        {
            Proveedor proveedor = new Proveedor();
            proveedor.id = id;
            proveedor.ciudad = ciudad;
            proveedor.nombre = nombre;
            return proveedor;
        }

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ModeloDominio", Name="Sucursal")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Sucursal : Empresa
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Sucursal.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="ciudad">Valor inicial de la propiedad ciudad.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        /// <param name="paginaweb">Valor inicial de la propiedad paginaweb.</param>
        /// <param name="logo">Valor inicial de la propiedad logo.</param>
        public static Sucursal CreateSucursal(global::System.Int32 id, global::System.String ciudad, global::System.String nombre, global::System.String paginaweb, global::System.Byte logo)
        {
            Sucursal sucursal = new Sucursal();
            sucursal.id = id;
            sucursal.ciudad = ciudad;
            sucursal.nombre = nombre;
            sucursal.paginaweb = paginaweb;
            sucursal.logo = logo;
            return sucursal;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String paginaweb
        {
            get
            {
                return _paginaweb;
            }
            set
            {
                OnpaginawebChanging(value);
                ReportPropertyChanging("paginaweb");
                _paginaweb = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("paginaweb");
                OnpaginawebChanged();
            }
        }
        private global::System.String _paginaweb;
        partial void OnpaginawebChanging(global::System.String value);
        partial void OnpaginawebChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte logo
        {
            get
            {
                return _logo;
            }
            set
            {
                OnlogoChanging(value);
                ReportPropertyChanging("logo");
                _logo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("logo");
                OnlogoChanged();
            }
        }
        private global::System.Byte _logo;
        partial void OnlogoChanging(global::System.Byte value);
        partial void OnlogoChanged();

        #endregion

    
    }

    #endregion

    
}
